### ISSUE TITLE
Thank referrer allows selecting social media without login

### ISSUE THREAD

**Issue by DoviLilling** [lilling/sweep-list#11]

**Comment by lilling** [comment]
@DoviLilling this can be on multiple social medias?

**Comment by DoviLilling** [comment]
No.
Still, it allows me to toggle Google+ on, although I'm not logged in to Google (Hmm... maybe I am?).
Does it let you say thanks on Facebook?

**Comment by lilling** [comment]
yes I didn't implement this kind of guard.

I think that it cant be on one occasion one style and in another occasion a different style of the login buttons

**Comment by DoviLilling** [comment]
You know what, let's remove this feature for now.
I'll gray it out in the user story.
DB structure stays the same.
