### ISSUE TITLE
When refreshing "Sweep list", this appears:

### ISSUE THREAD

**Issue by DoviLilling** [lilling/sweep-list#15]
![image](https://user-images.githubusercontent.com/36577564/39835018-77821c3e-53d7-11e8-8d9c-8d09ff07c27a.png)
It dissappears when the list is loaded, ofc.
1. Why is it shown?
2. Why does it try to connect to google?
Better have rolling widget.

**Comment by DoviLilling** [comment]
See bottom of screenshot.
You closed the issue without addressing the 1st question at all.

**Comment by lilling** [comment]
google connection - I don't know why. maybe its chrome itself.
1st question - its a bug so i fixed it. why do I need to explain what I did?

**Comment by DoviLilling** [comment]
Okay.
