### ISSUE TITLE
Deleted sweeps should have line through

### ISSUE THREAD

**Issue by DoviLilling** [lilling/sweep-list#16]
![image](https://user-images.githubusercontent.com/36577564/39836836-5d955a9c-53dd-11e8-8c5b-e8fdac9fefb7.png)

**Comment by lilling** [comment]
how can I delete a sweep?

**Comment by lilling** [comment]
so we concluded that a click on a sweep will open the edit window?

**Comment by DoviLilling** [comment]
Yes.
