### ISSUE TITLE
Hamburger

### ISSUE THREAD

**Issue by DoviLilling** [lilling/sweep-list#17]
- [x] To Do (home page) -> Don't Forget!
- [x] Live Sweeps -> Active Sweeps
- [ ] ~~Wins -> Wins Summary (#73)~~
- [x] Settings
- [x] Feedback -> Help & Feedback

anything else?

**Comment by lilling** [comment]
> anything else?

yeap: design for all of this.

**Comment by DoviLilling** [comment]
Currently, just do a simple menu (like the filter menu),
You have designs for Sweeps, Wins and Login Settings (login page).
Feedback should be a simple URL to "mailto:support@sweepimp.com".

**Comment by DoviLilling** [comment]
Feedback will be accessed through an icon in all pages (added to mockup).

**Comment by DoviLilling** [comment]
Mock up for hamburger in "Wins" page.
