### ISSUE TITLE
To Do - Display time left to next entry

### ISSUE THREAD

**Issue by DoviLilling** [lilling/sweep-list#20]

**Comment by DoviLilling** [comment]
Formula is frequency_days - (current_timestamp - last_entry_date)
Note: frequency_days is a whole number, the rest are dates.
Three categories:
Today -> Formula <= 0
Tomorrow -> Formula <= 1
Upcoming -> Formula > 1

**Comment by lilling** [comment]
I don't understand. can you please elaborate?

**Comment by DoviLilling** [comment]
Categories (right now, today, etc.) are irrelevant - I do this for you.
What you **do** need to do is to correctly calculate the "Time left to next entry".
The formula for that is:
frequency_days - (current_timestamp - last_entry_date)
Please note that frequency_days is a whole number, the rest are dates.
Also not that if the formula is negative, the entry time has passed, and we should present "0 Minutes Left"

**Comment by lilling** [comment]
if this issue is irrelevant please close it

**Comment by DoviLilling** [comment]
@lilling it is relevant, please read the **whole** comment.

**Comment by lilling** [comment]
is it not a part of #49 ?
