### ISSUE TITLE
Edit Sweep - Accordion and Use "sweep URL" column only

### ISSUE THREAD

**Issue by DoviLilling** [lilling/sweep-list#35]
**New sweep:**
- [x] Move URL to 1st page, populate "sweep URL" column.

**Edit sweep:**
- [x] Add URL field to top.
- [x] Remove URL from "Recurring entry".
- [x] "Recurring entry" doesn't need an accordion anymore.
- [x] Remove URL from "Share on social media".

**Dovi**
- [x] Update mock ups

**Comment by DoviLilling** [comment]
@lilling Did you really do everything?
App does not reflect the mockup (see sweep edit page and new sweep wizard pages)

**Comment by lilling** [comment]
@DoviLilling now its done

**Comment by DoviLilling** [comment]
**New sweep** does not resemble the mock ups, the same URL should repeat on "Recurring Entry" and "Share on My Social Media" pages.
It's OK if it will also show three times on edit page.
**Edit Sweep** does not have a accordion for "Recurring Entry"

**Comment by lilling** [comment]
@DoviLilling so the user will be able to edit 3 times sweep_url field? it doesn't make any sense.
you wrote: 

> "Recurring entry" doesn't need an accordion anymore

**Comment by DoviLilling** [comment]
@lilling fine, make it read only.
Without an accordion, it looks really bad. The best thing will be if the accordion will open if the option is on.

**Comment by lilling** [comment]
toggle top of arrow
