### ISSUE TITLE
Paging in sweep list

### ISSUE THREAD

**Issue by DoviLilling** [lilling/sweep-list#4]

**Comment by DoviLilling** [comment]
Add last sweep presented to get sweeps calls (live_user_sweeps/*, ended_user_sweeps/*, won_user_sweeps/*).

**Comment by lilling** [comment]
@DoviLilling please notice that I opened a new branch for this issue and started to work on it.
please do your work there also.

**Comment by DoviLilling** [comment]
I did also, but did not commit.
Can I do it on my branch, then we merge them, then merge the merged one to master?

**Comment by lilling** [comment]
I think we better do it asap.
