### ISSUE TITLE
Weird scrolling behavior

### ISSUE THREAD

**Issue by DoviLilling** [lilling/sweep-list#51]
- [x] Scrolling does not work on PC, just in mobile mode.
- [x] There are two scroll bars in PC mode.
- [x] Scrolling to the end in mobile, and then scrolling more, makes the header ("Don't Forget!") disappear (possibly connected to previous task).

**Comment by lilling** [comment]
roll back to previous regular behavior. without any sticky headers

**Comment by DoviLilling** [comment]
Scrolling does not bring the next batch.
