### ISSUE TITLE
Add Sweep issues

### ISSUE THREAD

**Issue by DoviLilling** [lilling/sweep-list#53]
- [x] Scroll bar on "Share on Social"
- [x] Scroll bar on "Thank referrer"
- [x] "Share" - disabling the option does not disable the social media selection enablers.

When option (share, recurring, thank) is not enabled, all text should reflect that, not just the inputs. Relevant on:
- [x] Recurring
- [x] Share

**Comment by lilling** [comment]
> all text should reflect that

how?
