### ISSUE TITLE
Add popup with the sweeps tasks to be done

### ISSUE THREAD

**Issue by DoviLilling** [lilling/sweep-list#69]
Edit sweep page will also have essential sweep data (name, end date) and buttons for entry, FB share, TWT share etc.
If a task is done, a green check mark will appear. A user can press the share again, but a spam warning popup will appear for sharing actions.
This will add to the user's understanding and remove clutter.

**Comment by lilling** [comment]
@DoviLilling why not just hide the share buttons?

**Comment by DoviLilling** [comment]
Never mind this issue.
