### ISSUE TITLE
Problems with share buttons

### ISSUE THREAD

**Issue by DoviLilling** [lilling/sweep-list#76]
- [x] Does not share the sweep URL, but the page URL (app.sweepimp.com), with a nice "[ShareButtons]: Sharing link '<sweep URL>' is invalid!" error in the consule.
- [x] Pinterest does not share **any** URL.
- [x] Does not remove sweep from list after all tasks are done (see 1st sweep on list - test 5).
- [x] Does not look very well (image attached):
1. Covers text
2. 2nd text is clipped.
![image](https://user-images.githubusercontent.com/36577564/45382591-65000700-b611-11e8-9e4b-f7275b6b91f0.png)

**Comment by DoviLilling** [comment]
BTW, looks great on "Active Sweeps" (except for vertical alignment), but still does not share what it should.

**Comment by lilling** [comment]
I removed actions from active sweeps also.

**Comment by DoviLilling** [comment]
Does not remove sweep from list after all tasks are done (see 1st sweep on list - test 5).

**Comment by lilling** [comment]
fixed
